### ISSUE TITLE
[FR] Save the tree

### ISSUE THREAD

**Issue by Lyr3x** [biolab/orange3-associate#22]
A function which returns the fp_tree would be very nice (to print it out).

**Comment by kernc** [comment]
fp_tree? Do you mean in Orange widgets or in scripts? Widgets don't reveal the computed FP-tree. Do you mean the results (frequent itemsets / rules)?

**Comment by Lyr3x** [comment]
Ah sorry, forgot to specify. Im talking about scripts.
To clarify:
I'm interested in printing the fp_tree which is created during mining process (for visualisation of the specific tree in my documentation). I would to print the `root` in def `_fp_tree(db, min_support)` and OneHot decode the elements to make it readable.
For now i am printing the root and the decoded values separately, because im not sure how to exactly return the created tree.

Example of the tree i am talking about:

`{   0: {   7: {},
           10: {},
           11: {1467: {}},
           13: {1467: {}},
           14: {1467: {}},
           15: {1467: {}},
           16: {1467: {}},
           17: {5428: {}},
           18: {}},
}`

**Comment by kernc** [comment]
> I'm interested in printing the fp_tree which is created during mining process (for visualisation of the specific tree in my documentation). I would to print the `root` in def `_fp_tree(db, min_support)` and OneHot decode the elements to make it readable.

Normally, several FP-trees are constructed during a run of the frequent itemsets search. For a one-off visualization something for your documentation, I suggest you locally amend the function directly. Instead of printing with `print()`, you can save all `root`s into a list you at the end decode and print/query, roughly like so:
```py
from copy import deepcopy

roots = []

def _fp_tree(db, min_support):
    ...
    roots.append(deepcopy(root))
    ...

def frequent_itemsets(X, min_support=.2):
    ...
    # do something with roots
    my_custom_function(roots)
```
Let me know if this is too unclear. I don't see how something like this would be in scope for the library, though.

**Comment by ajdapretnar** [comment]
I assume this resolved. Also inactive for some time now.
