### ISSUE TITLE
Worthless Erroneous Results from uploaded CSV file

### ISSUE THREAD

**Issue by M4x28** [biolab/orange3-associate#62]
##### Associate version

1.3.0

##### Orange version

3.36.2

##### Expected behavior
Frequent Itemsets and Association Rules Analyses

##### Actual behavior
worthless erroneous results

##### Steps to reproduce the behavior
1) Load data into CSV File Import
2) Connect to Frequent Itemsets and try analysis
3) Connect to Association Rules and try analysis

##### Additional info (worksheets, data, screenshots, ...)
Orange Schema
![image](https://github.com/biolab/orange3-associate/assets/64036726/24043ef5-10c7-41b6-abf8-f89e07a4d02d)
Frequent Itemsets
![image](https://github.com/biolab/orange3-associate/assets/64036726/704640d4-a7ba-47e3-9027-f0171753ec5e)
Association Rules
![image](https://github.com/biolab/orange3-associate/assets/64036726/1f3e8385-2d7f-4ffa-9238-bfa26f328cb2)
Data Table
![image](https://github.com/biolab/orange3-associate/assets/64036726/abf71003-054d-4800-8bde-b7defd3ec8b6)
CSV Data Pivot like Market Basket dataset
[pivot.csv](https://github.com/biolab/orange3-associate/files/14967564/pivot.csv)
CSV Data like Foofmart 2000 dataset
[dataset.csv](https://github.com/biolab/orange3-associate/files/14967574/dataset.csv)

**Comment by janezd** [comment]
Frequent Itemsets and Association Rules must be run on basket data. Open widget Datasets, find Foodmart and try it.

Data in attribute-value form (like the one that you use) must be used when we don't want to treat a "0" value as special. They find relations like "didn't buy bread -> didn't buy ham", and there are naturally many more of them. This is by design.

In your case, 0 is a special value, so the data must be given like this: https://file.biolab.si/datasets/foodmart.basket.
